server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          gitee:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'

            client-authentication-method: post # default: basic
            scope: user_info # default: emptySet

            client-name: gitee_login # optional
          demo:
            client-id: demo-client-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}' # http:8080/login/oauth/code/demo
            client-name: demos里的 oauth2-auth-server

        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: id
          demo:
            authorization-uri: http://authServer.com:8081/oauth/authorize # host 文件中 authServer 对应着 127.0.0.1
            token-uri: http://authServer.com:8081/oauth/token
            user-info-uri: http://resourceServer.com:8000/user
            user-name-attribute: userName
