server:
  port: 80

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

messages:
  base-uri: http://resourceServer.com:8000/messages

demo:
  auth:
    host: authServer.com
    port: 8081
    uri: http://${demo.auth.host:localhost}:${demo.auth.port:8081}
  resource:
    host: resourceServer.com
    port: 8000
    uri: http://${demo.resource.host:localhost}:${demo.resource.port:8000}

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:               # 需要把 demo 相关的配置到 demo 的授权服务器里，类似在QQ的开发者页面注册应用
          demo-auth-code:
            client-name: demo-授权码模式
            provider: demo
            client-id: demo-client-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/demo' # 默认 {baseUrl}/{action}/oauth2/code/{registrationId} 即 http://demo.com/login/oauth/code/demo
          demo-client-creds:  # 客户端模式
            client-name: demo-客户端模式
            provider: demo
            client-id: demo-client-id
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: message.read,message.write
          demo-password:      # oauth2-密码模式
            client-name: demo-密码模式
            provider: demo
            client-id: demo-client-id
            client-secret: secret
            authorization-grant-type: password
            scope: message.read,message.write  
            
          github:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
            client-name: github 登录

          gitee:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: post    # default: basic
            scope: user_info                      # default: emptySet
            client-name: gitee 登录               # optional

          qq:
            client-id: xxx
            client-secret: xxxx
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}' # http://demo.com/login/oauth/code/qq
            client-name: QQ 登录

        provider:
          demo:
            authorization-uri: ${demo.auth.uri}/oauth/authorize # host 文件中 authServer 对应着 127.0.0.1
            token-uri: ${demo.auth.uri}/oauth/token
            user-info-uri: ${demo.resource.uri}/user
            user-name-attribute: userName
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            user-name-attribute: id
          qq:
            authorization-uri: https://graph.qq.com/oauth2.0/authorize # host 文件中 authServer 对应着 127.0.0.1
            token-uri: https://graph.qq.com/oauth2.0/token
            user-info-uri: https://graph.qq.com/user/get_user_info
            user-name-attribute: nickname