server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: ${mockwebserver.url}/.well-known/jwks.json
          jwk-set-uri: http://127.0.0.1:8081/.well-known/jwks.json