server:
  port: 8000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: ${mockwebserver.url}/.well-known/jwks.json
          jwk-set-uri: http://authServer.com:8081/.well-known/jwks.json